// utils/artists/artistHelpers.ts
import { Artist } from "@/interfaces/Artist";

/**
 * Simulación de un "mock" de artistas con datos
 * completos (imagen, descripción, links, etc.).
 * Incluye 2 artistas por cada letra del abecedario.
 */
const mockArtists: Artist[] = [
  // A
  {
    id: 1,
    name: "Ariana Grande",
    image: "https://picsum.photos/200/200?random=101",
    description: "Cantante pop estadounidense muy famosa.",
    likes: 120,
    instagramURL: "https://instagram.com/arianagrande",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/66CXWjxzNUsdJxJ2JdwvnR",
    creationDate: "2025-01-01",
  },
  {
    id: 2,
    name: "Adele",
    image: "https://picsum.photos/200/200?random=102",
    description: "Cantante y compositora británica.",
    likes: 300,
    instagramURL: "https://instagram.com/adele",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY",
    creationDate: "2025-02-10",
  },
  // B
  {
    id: 3,
    name: "Beyoncé",
    image: "https://picsum.photos/200/200?random=103",
    description: "Cantante, compositora y actriz estadounidense.",
    likes: 999,
    instagramURL: "https://instagram.com/beyonce",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m",
    creationDate: "2025-02-15",
  },
  {
    id: 4,
    name: "Bruno Mars",
    image: "https://picsum.photos/200/200?random=104",
    description: "Cantante, compositor y productor estadounidense.",
    likes: 450,
    instagramURL: "https://instagram.com/brunomars",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C",
    creationDate: "2025-03-01",
  },
  // C
  {
    id: 5,
    name: "Charlie Puth",
    image: "https://picsum.photos/200/200?random=105",
    description: "Cantante y productor estadounidense, famoso por 'See You Again'.",
    likes: 280,
    instagramURL: "https://instagram.com/charlieputh",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6VuMaDnrHyPL1p4EHjYLi7",
    creationDate: "2025-03-10",
  },
  {
    id: 6,
    name: "Chris Brown",
    image: "https://picsum.photos/200/200?random=106",
    description: "Cantante y bailarín estadounidense.",
    likes: 210,
    instagramURL: "https://instagram.com/chrisbrownofficial",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/7bXgB6jMjp9ATFy66eO08Z",
    creationDate: "2025-03-12",
  },
  // D
  {
    id: 7,
    name: "David Guetta",
    image: "https://picsum.photos/200/200?random=107",
    description: "DJ y productor francés de música electrónica.",
    likes: 320,
    instagramURL: "https://instagram.com/davidguetta",
    soundcloudURL: "https://soundcloud.com/davidguetta",
    spotifyURL: "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
    creationDate: "2025-03-15",
  },
  {
    id: 8,
    name: "Dua Lipa",
    image: "https://picsum.photos/200/200?random=108",
    description: "Cantante y compositora británica de pop.",
    likes: 410,
    instagramURL: "https://instagram.com/dualipa",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we",
    creationDate: "2025-03-20",
  },
  // E
  {
    id: 9,
    name: "Ed Sheeran",
    image: "https://picsum.photos/200/200?random=109",
    description: "Cantautor británico de folk-pop.",
    likes: 500,
    instagramURL: "https://instagram.com/teddysphotos",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V",
    creationDate: "2025-03-25",
  },
  {
    id: 10,
    name: "Elton John",
    image: "https://picsum.photos/200/200?random=110",
    description: "Cantautor y pianista británico, icono de la música pop-rock.",
    likes: 350,
    instagramURL: "https://instagram.com/eltonjohn",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b",
    creationDate: "2025-04-01",
  },
  // F
  {
    id: 11,
    name: "Freddie Mercury",
    image: "https://picsum.photos/200/200?random=111",
    description: "Vocalista de la banda Queen, uno de los mejores cantantes de la historia.",
    likes: 1000,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1r4hJ1hszHOb9ADWhp6Koi",
    creationDate: "2025-04-05",
  },
  {
    id: 12,
    name: "Florence Welch",
    image: "https://picsum.photos/200/200?random=112",
    description: "Cantante principal de Florence + The Machine.",
    likes: 220,
    instagramURL: "https://instagram.com/florence",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1moxjboGR7GNWYIMWsRjgG",
    creationDate: "2025-04-10",
  },
  // G
  {
    id: 13,
    name: "Galantis",
    image: "https://picsum.photos/200/200?random=113",
    description: "Dúo sueco de música electrónica.",
    likes: 190,
    instagramURL: "https://instagram.com/wearegalantis",
    soundcloudURL: "https://soundcloud.com/wearegalantis",
    spotifyURL: "https://open.spotify.com/artist/4sTQVOfp9vEMCemLw50sbu",
    creationDate: "2025-04-15",
  },
  {
    id: 14,
    name: "Green Day",
    image: "https://picsum.photos/200/200?random=114",
    description: "Banda estadounidense de punk rock.",
    likes: 450,
    instagramURL: "https://instagram.com/greenday",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY",
    creationDate: "2025-04-20",
  },
  // H
  {
    id: 15,
    name: "Harry Styles",
    image: "https://picsum.photos/200/200?random=115",
    description: "Cantante británico, exmiembro de One Direction.",
    likes: 600,
    instagramURL: "https://instagram.com/harrystyles",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3",
    creationDate: "2025-04-25",
  },
  {
    id: 16,
    name: "Hailee Steinfeld",
    image: "https://picsum.photos/200/200?random=116",
    description: "Actriz y cantante estadounidense.",
    likes: 170,
    instagramURL: "https://instagram.com/haileesteinfeld",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
    creationDate: "2025-05-01",
  },
  // I
  {
    id: 17,
    name: "Imagine Dragons",
    image: "https://picsum.photos/200/200?random=117",
    description: "Banda estadounidense de pop rock y rock alternativo.",
    likes: 480,
    instagramURL: "https://instagram.com/imaginedragons",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q",
    creationDate: "2025-05-05",
  },
  {
    id: 18,
    name: "Iggy Azalea",
    image: "https://picsum.photos/200/200?random=118",
    description: "Rapera y compositora australiana.",
    likes: 130,
    instagramURL: "https://instagram.com/thenewclassic",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/166DzPmyXk2io4RAwHpcoA",
    creationDate: "2025-05-10",
  },
  // J
  {
    id: 19,
    name: "Jennifer Lopez",
    image: "https://picsum.photos/200/200?random=119",
    description: "Cantante, actriz y bailarina estadounidense.",
    likes: 700,
    instagramURL: "https://instagram.com/jlo",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/2DlGxzQSjYe5N6G9nkYghR",
    creationDate: "2025-05-15",
  },
  {
    id: 20,
    name: "John Legend",
    image: "https://picsum.photos/200/200?random=120",
    description: "Cantante, compositor y pianista estadounidense.",
    likes: 250,
    instagramURL: "https://instagram.com/johnlegend",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5yxyJsFanEAuwSM5kOuZKc",
    creationDate: "2025-05-20",
  },
  // K
  {
    id: 21,
    name: "Katy Perry",
    image: "https://picsum.photos/200/200?random=121",
    description: "Cantautora estadounidense de pop.",
    likes: 500,
    instagramURL: "https://instagram.com/katyperry",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X",
    creationDate: "2025-05-25",
  },
  {
    id: 22,
    name: "Kendrick Lamar",
    image: "https://picsum.photos/200/200?random=122",
    description: "Rapper y compositor estadounidense.",
    likes: 420,
    instagramURL: "https://instagram.com/kendricklamar",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg",
    creationDate: "2025-06-01",
  },
  // L
  {
    id: 23,
    name: "Lana Del Rey",
    image: "https://picsum.photos/200/200?random=123",
    description: "Cantautora estadounidense de indie pop.",
    likes: 360,
    instagramURL: "https://instagram.com/lanadelrey",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/00FQb4jTyendYWaN8pK0wa",
    creationDate: "2025-06-05",
  },
  {
    id: 24,
    name: "Lil Nas X",
    image: "https://picsum.photos/200/200?random=124",
    description: "Rapper y cantante estadounidense, famoso por 'Old Town Road'.",
    likes: 230,
    instagramURL: "https://instagram.com/lilnasx",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq",
    creationDate: "2025-06-10",
  },
  // M
  {
    id: 25,
    name: "Mariah Carey",
    image: "https://picsum.photos/200/200?random=125",
    description: "Cantante estadounidense conocida por su rango vocal.",
    likes: 550,
    instagramURL: "https://instagram.com/mariahcarey",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/4iHNK0tOyZPYnBU7nGAgpQ",
    creationDate: "2025-06-15",
  },
  {
    id: 26,
    name: "Miley Cyrus",
    image: "https://picsum.photos/200/200?random=126",
    description: "Cantante y actriz estadounidense.",
    likes: 410,
    instagramURL: "https://instagram.com/mileycyrus",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6",
    creationDate: "2025-06-20",
  },
  // N
  {
    id: 27,
    name: "Niall Horan",
    image: "https://picsum.photos/200/200?random=127",
    description: "Cantante irlandés, ex One Direction.",
    likes: 220,
    instagramURL: "https://instagram.com/niallhoran",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1Hsdzj7Dlq2I7tHP7501T4",
    creationDate: "2025-06-25",
  },
  {
    id: 28,
    name: "Nicki Minaj",
    image: "https://picsum.photos/200/200?random=128",
    description: "Rapera, cantante y compositora trinitense-estadounidense.",
    likes: 570,
    instagramURL: "https://instagram.com/nickiminaj",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/0hCNtLu0JehylgoiP8L4Gh",
    creationDate: "2025-07-01",
  },
  // O
  {
    id: 29,
    name: "OneRepublic",
    image: "https://picsum.photos/200/200?random=129",
    description: "Banda estadounidense de pop rock.",
    likes: 330,
    instagramURL: "https://instagram.com/onerepublic",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ",
    creationDate: "2025-07-05",
  },
  {
    id: 30,
    name: "Olivia Rodrigo",
    image: "https://picsum.photos/200/200?random=130",
    description: "Cantautora y actriz estadounidense.",
    likes: 490,
    instagramURL: "https://instagram.com/oliviarodrigo",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG",
    creationDate: "2025-07-10",
  },
  // P
  {
    id: 31,
    name: "Post Malone",
    image: "https://picsum.photos/200/200?random=131",
    description: "Rapper, cantante y compositor estadounidense.",
    likes: 680,
    instagramURL: "https://instagram.com/postmalone",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/246dkjvS1zLTtiykXe5h60",
    creationDate: "2025-07-15",
  },
  {
    id: 32,
    name: "Pharrell Williams",
    image: "https://picsum.photos/200/200?random=132",
    description: "Cantante, compositor y productor estadounidense.",
    likes: 410,
    instagramURL: "https://instagram.com/pharrell",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8",
    creationDate: "2025-07-20",
  },
  // Q
  {
    id: 33,
    name: "Queen",
    image: "https://picsum.photos/200/200?random=133",
    description: "Banda británica de rock, liderada por Freddie Mercury.",
    likes: 2000,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d",
    creationDate: "2025-07-25",
  },
  {
    id: 34,
    name: "Quavo",
    image: "https://picsum.photos/200/200?random=134",
    description: "Rapper estadounidense, miembro de Migos.",
    likes: 210,
    instagramURL: "https://instagram.com/quavohuncho",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/0VRj0yCOv2FXJNP47XQnx5",
    creationDate: "2025-08-01",
  },
  // R
  {
    id: 35,
    name: "Rihanna",
    image: "https://picsum.photos/200/200?random=135",
    description: "Cantante, compositora y empresaria barbadense.",
    likes: 900,
    instagramURL: "https://instagram.com/badgalriri",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H",
    creationDate: "2025-08-05",
  },
  {
    id: 36,
    name: "Rod Stewart",
    image: "https://picsum.photos/200/200?random=136",
    description: "Cantante y compositor británico de rock/pop.",
    likes: 150,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6QrQ7OrISRYIfS5mtacaw2",
    creationDate: "2025-08-10",
  },
  // S
  {
    id: 37,
    name: "Shakira",
    image: "https://picsum.photos/200/200?random=137",
    description: "Cantante, compositora y productora colombiana.",
    likes: 800,
    instagramURL: "https://instagram.com/shakira",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp",
    creationDate: "2025-08-15",
  },
  {
    id: 38,
    name: "Sia",
    image: "https://picsum.photos/200/200?random=138",
    description: "Cantautora australiana, conocida por su estilo vocal único.",
    likes: 340,
    instagramURL: "https://instagram.com/siamusic",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5WUlDfRSoLAfcVSX1WnrxN",
    creationDate: "2025-08-20",
  },
  // T
  {
    id: 39,
    name: "Taylor Swift",
    image: "https://picsum.photos/200/200?random=139",
    description: "Cantante y compositora estadounidense de country/pop.",
    likes: 1500,
    instagramURL: "https://instagram.com/taylorswift",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02",
    creationDate: "2025-08-25",
  },
  {
    id: 40,
    name: "The Weeknd",
    image: "https://picsum.photos/200/200?random=140",
    description: "Cantante, compositor y productor canadiense.",
    likes: 750,
    instagramURL: "https://instagram.com/theweeknd",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ",
    creationDate: "2025-09-01",
  },
  // U
  {
    id: 41,
    name: "U2",
    image: "https://picsum.photos/200/200?random=141",
    description: "Banda de rock irlandesa, liderada por Bono.",
    likes: 650,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/51Blml2LZPmy7TTiAg47vQ",
    creationDate: "2025-09-05",
  },
  {
    id: 42,
    name: "Usher",
    image: "https://picsum.photos/200/200?random=142",
    description: "Cantante, compositor y bailarín estadounidense de R&B.",
    likes: 380,
    instagramURL: "https://instagram.com/usher",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4",
    creationDate: "2025-09-10",
  },
  // V
  {
    id: 43,
    name: "Van Halen",
    image: "https://picsum.photos/200/200?random=143",
    description: "Banda estadounidense de hard rock.",
    likes: 460,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/2cnMpRsOVqtPMfq7YiFE6K",
    creationDate: "2025-09-15",
  },
  {
    id: 44,
    name: "Van Morrison",
    image: "https://picsum.photos/200/200?random=144",
    description: "Cantante y compositor norirlandés.",
    likes: 210,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/44NX2ffIYHr6D4n7RaZF7A",
    creationDate: "2025-09-20",
  },
  // W
  {
    id: 45,
    name: "Wiz Khalifa",
    image: "https://picsum.photos/200/200?random=145",
    description: "Rapper, cantante y compositor estadounidense.",
    likes: 400,
    instagramURL: "https://instagram.com/wizkhalifa",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop",
    creationDate: "2025-09-25",
  },
  {
    id: 46,
    name: "Weezer",
    image: "https://picsum.photos/200/200?random=146",
    description: "Banda de rock alternativo estadounidense.",
    likes: 210,
    instagramURL: "https://instagram.com/weezer",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/3jOstUTkEu2JkjvRdBA5Gu",
    creationDate: "2025-10-01",
  },
  // X
  {
    id: 47,
    name: "X Ambassadors",
    image: "https://picsum.photos/200/200?random=147",
    description: "Banda estadounidense de rock alternativo.",
    likes: 140,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/3mIj9lX2MWuHmhNCA7LSCW",
    creationDate: "2025-10-05",
  },
  {
    id: 48,
    name: "Xzibit",
    image: "https://picsum.photos/200/200?random=148",
    description: "Rapper, actor y presentador de televisión estadounidense.",
    likes: 90,
    instagramURL: "https://instagram.com/xzibit",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/1whpM4B8knci6RrN7mQ4gK",
    creationDate: "2025-10-10",
  },
  // Y
  {
    id: 49,
    name: "Yungblud",
    image: "https://picsum.photos/200/200?random=149",
    description: "Cantante y compositor de rock alternativo británico.",
    likes: 240,
    instagramURL: "https://instagram.com/yungblud",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6Ad91Jof8Niiw0lGLLi3NW",
    creationDate: "2025-10-15",
  },
  {
    id: 50,
    name: "Yo-Yo Ma",
    image: "https://picsum.photos/200/200?random=150",
    description: "Violonchelista estadounidense de origen chino.",
    likes: 80,
    instagramURL: "",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/5lCUiSrtZkXZ7ES0CqPyq7",
    creationDate: "2025-10-20",
  },
  // Z
  {
    id: 51,
    name: "Zedd",
    image: "https://picsum.photos/200/200?random=151",
    description: "DJ y productor de origen ruso-alemán.",
    likes: 270,
    instagramURL: "https://instagram.com/zedd",
    soundcloudURL: "https://soundcloud.com/zedd",
    spotifyURL: "https://open.spotify.com/artist/2qxJFvFYMEDqd7ui6kSAcq",
    creationDate: "2025-10-25",
  },
  {
    id: 52,
    name: "Zac Brown Band",
    image: "https://picsum.photos/200/200?random=152",
    description: "Banda estadounidense de country/folk.",
    likes: 190,
    instagramURL: "https://instagram.com/zacbrownband",
    soundcloudURL: "",
    spotifyURL: "https://open.spotify.com/artist/6yJCxee7QumYr820xdIsjo",
    creationDate: "2025-10-30",
  },
];

/** Retorna todo el array con datos completos. */
export function getAllArtists(): Artist[] {
  return mockArtists;
}

/** Busca un artista por nombre EXACTO (case-insensitive). */
export function getArtistByName(name: string): Artist | null {
  const lowerName = name.toLowerCase();
  const found = mockArtists.find(
    (artist) => artist.name.toLowerCase() === lowerName
  );
  return found ?? null;
}

/** Retorna los artistas cuyo nombre contenga `query` (búsqueda parcial). */
export function searchArtistsByName(query: string): Artist[] {
  const lower = query.toLowerCase();
  return mockArtists.filter((artist) =>
    artist.name.toLowerCase().includes(lower)
  );
}
