import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZES, FONTS, RADIUS } from "@/styles/globalStyles";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundLight },
  loaderWrapper: { flex: 1, justifyContent: "center", alignItems: "center" },
  scrollContent: { paddingBottom: 32 },

  titleRow: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  titleCol: {
    flex: 1,
    marginRight: 8,
  },
  title: {
    flex: 1,
    marginRight: 8,
    fontFamily: FONTS.titleBold,
    fontSize: FONT_SIZES.titleMain,
    color: COLORS.textPrimary,
    textDecorationLine: "underline",
  },
  dateUnderTitle: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  heartBtn: {},

  heroImageWrapper: {
    position: "relative",
    width: "100%",
    aspectRatio: 16 / 9,
    marginBottom: 18,
  },
  heroImage: {
    width: "100%",
    aspectRatio: 16 / 9,
    resizeMode: "cover",
  },

  eventInfoBlockImproved: {
    backgroundColor: "rgba(245,248,255,0.96)",
    borderRadius: RADIUS.card,
    paddingVertical: 38,
    paddingHorizontal: 24,
    marginHorizontal: 12,
  marginTop: 12,
    marginBottom: 24,
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    minHeight: 180,
    maxHeight: 400,
    overflow: "visible",
    justifyContent: "center",
  },

  artistRowImproved: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    maxWidth: "100%",
  },
  seeAllArtistsBtn: {
    marginLeft: 8,
    backgroundColor: "#2196F3",
    borderRadius: 14,
    paddingVertical: 2,
    paddingHorizontal: 10,
    alignSelf: "center",
  },
  seeAllArtistsText: {
    color: "#fff",
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    fontWeight: "bold",
  },
  artistsModalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  artistsModalContent: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 24,
    minWidth: 260,
    maxWidth: 340,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    alignItems: "center",
  },
  artistsModalTitle: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.subTitle,
    color: COLORS.textPrimary,
    fontWeight: "bold",
    marginBottom: 12,
  },
  artistsModalItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  artistsModalName: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
  },
  artistsModalCloseBtn: {
    marginTop: 16,
    backgroundColor: COLORS.negative,
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 18,
  },
  artistsModalCloseText: {
    color: "#fff",
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    fontWeight: "bold",
  },
  artistLabelImproved: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    fontWeight: "bold",
    marginRight: 2,
  },
  artistNameImproved: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    flex: 1,
  },
  /* Compact info row with small icon circle */
  infoRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  iconCircle: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: COLORS.cardBg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    elevation: 1,
  },
  infoLabel: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.body + 1,
    color: COLORS.textPrimary,
    fontWeight: "700",
    marginRight: 8,
  },
  infoValue: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body + 1,
    color: COLORS.primary,
    flex: 1,
  },

  // Container to stack "Fecha" (top) and "Horario" (bottom) next to the calendar icon
  twoLineContainer: {
    flex: 1,
    flexDirection: "column",
  },
  // Inline value style when nesting inside a label Text (keeps weight/color consistent)
  infoValueInline: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body + 1,
    color: COLORS.primary,
    fontWeight: "normal",
  },

  dataRowImproved: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  dataLabelImproved: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.subTitle + 2,
    color: COLORS.textPrimary,
    fontWeight: "bold",
    marginRight: 6,
  },
  dataValueImproved: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.subTitle + 2,
    color: COLORS.primary,
    marginRight: 10,
  },
  arrivalBtnImproved: {
    backgroundColor: COLORS.primary,
    borderRadius: 22,
    paddingVertical: 7,
    paddingHorizontal: 22,
    marginLeft: 8,
    alignSelf: "center",
    elevation: 2,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  arrivalBtnTextImproved: {
    color: COLORS.cardBg,
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.body + 1,
    fontWeight: "bold",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0,0,0,0.06)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },

  tagsRowImproved: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    marginBottom: 12, // separar badges de la imagen del evento
    marginLeft: 12, // separar badges del borde izquierdo
  },
  tagItemImproved: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.backgroundLight,
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 6,
    borderWidth: 1,
    borderColor: COLORS.info,
    // sombra sutil
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  tagTextImproved: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.primary,
    fontWeight: "bold",
  },
  lgbtTag: {
    backgroundColor: COLORS.primary,
    borderColor: "transparent",
    paddingVertical: 6,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    elevation: 3,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  lgbtTagText: {
    color: COLORS.cardBg,
    fontWeight: "700",
    fontSize: FONT_SIZES.body,
    marginLeft: 8,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  lgbtFlagBox: {
    width: 22,
    height: 14,
    borderRadius: 3,
    backgroundColor: COLORS.cardBg,
    overflow: "hidden",
    flexDirection: "column",
  },
  flagStripe: {
    flex: 1,
    width: "100%",
  },
  afterTag: {
    backgroundColor: "#FFEDD5", // cálido
    borderColor: "#FDBA74",
    borderWidth: 1,
    borderRadius: 999,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  afterTagText: {
    color: "#B45309",
    fontWeight: "800",
    letterSpacing: 0.5,
  },

  videoSection: { marginTop: 16, marginBottom: 8, paddingHorizontal: 16 },
  videoWrapper: {
    overflow: "hidden",
    borderRadius: RADIUS.card,
    backgroundColor: "transparent",
    aspectRatio: 16 / 9,
    width: "100%",
  },
  webview: { width: "100%", height: "100%", backgroundColor: "transparent" },

  /* Media blocks spacing */
  mediaBlock: {
    marginTop: 12,
    marginBottom: 12,
  },
  /* media wrapper fixed ahora usa aspectRatio para ajustar exactamente al area del player
     y no deja fondo negro debajo. Mantener background transparente para evitar barras. */
  mediaWrapperFixed: {
    width: "100%",
    aspectRatio: 16 / 9,
    overflow: "hidden",
    borderRadius: RADIUS.card,
    backgroundColor: "transparent",
  },

  description: {
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 20,
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
    lineHeight: FONT_SIZES.body * 1.5,
    textAlign: "justify",
  },

  ticketSection: {
    backgroundColor: COLORS.cardBg,
    borderRadius: RADIUS.card,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 24,
    elevation: 2,
    overflow: "visible",
  },
  sectionTitle: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.subTitle,
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  dayBlock: { marginBottom: 16, overflow: "visible", position: "relative" },
  clearDayBtn: {
    position: "absolute",
    top: -8,
    right: 8,
    backgroundColor: COLORS.negative,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
  },
  dayLabel: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.body,
    color: COLORS.info,
    marginBottom: 8,
  },
  subtotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  subtotalText: {
    fontFamily: FONTS.subTitleMedium,
    fontSize: FONT_SIZES.body,
    color: COLORS.textPrimary,
  },
  buyButton: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.card,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  buyButtonFull: {
    backgroundColor: "#0f172a",
    borderRadius: RADIUS.card,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  buyButtonDisabled: {
    opacity: 0.5,
  },
  buyButtonText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.button,
    color: COLORS.cardBg,
  },

  errorText: {
    fontFamily: FONTS.bodyRegular,
    fontSize: FONT_SIZES.body,
    color: COLORS.negative,
  },
});
